version: "3.4"
services:
   db:
      image: mongo
      restart: always
      container_name: mongo-db
      ports:
        - 27017:27017
      environment:
         MONGO_INITDB_ROOT_USERNAME: admin
         MONGO_INITDB_ROOT_PASSWORD: admin
         MONGO_INITDB_DATABASE: url_shortener